title: Zanjeel T. Sahi
logo: /assets/img/logo.png
name: Zanjeel T. Sahi
site_title: Zanjeel T. Sahi
description: View more Projects on my Github
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_user_page: true
  owner_url: https://github.com/zanjeel
  repository_url: https://github.com/zanjeel
  repository_nwo: zanjeel
